### ISSUE TITLE
Метод kinopoisk.get_film выдает ошибку

### ISSUE THREAD

**Issue by SonaR83** [Ulbwaa/KinoPoiskAPI#3]
Добрый день! Метод kinopoisk.get_film выдает ошибку:
Traceback (most recent call last):
  File "D:/OneDrive/Python/Projects/pythonKimopoisk38/get_film.py", line 5, in <module>
    tenet = kinopoisk.get_film(666)
  File "D:\OneDrive\Python\Projects\pythonKimopoisk38\submodules\kinopoisk_api.py", line 88, in get_film
    return FILM(data)
  File "D:\OneDrive\Python\Projects\pythonKimopoisk38\submodules\kinopoisk_api.py", line 28, in __init__
    self.secret_url = 'https:/' + data['secret']['data'][0]['iframe_src']
KeyError: 'data'

1. Установку провел в соответствии с рекомендациями
2. Выполнял через Pycharm 2021.3.2 (community edition)
3. В настройках виртуальной среды выставлял версию 3.8 (а до этого 3.10 - все безрезультатно)

from submodules.kinopoisk_api import KP

kinopoisk = KP(token='токен')

tenet = kinopoisk.get_film(666) # форсаж

print(tenet.ru_name, tenet.year)
print(", ".join(tenet.genres))
print(", ".join(tenet.countries))
print(tenet.tagline)

**Comment by vir2ozz2009** [comment]
точно такая же ошибка, видимо устала код
